#!/usr/bin/env bash
# A Bash script that loops from 1 to 10
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
# Requirement: You must use the while loop (for and until are forbidden) and You must use the if, elif and else statements


LIMIT=10
n=1

while [ $n -le $LIMIT ]
do
	if [ $n -eq 4 ]
	then
		echo "bad luck"
	elif [ $n -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(("n+=1"))
done
