#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
# Requirements: You must use the while loop (for and until are forbidden) and You must use the case statement


LIMIT=20
num=1

while [ $num -le $LIMIT ]
do
	case $num in
		4)
			echo "$num"
			echo "bad luck from China"
			;;
		9)
			echo "$num"
			echo "bad luck from Japan"
			;;
		17)
			echo "$num"
			echo "bad luck from Italy"
			;;
		*)
			echo "$num"
			;;
	esac
	((num++))
done
