#!/usr/bin/env bash
# This bash script configures an Ubuntu server as follows:
# **** localhost resolves to 127.0.0.2
# **** facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.nw
echo "127.0.0.2		localhost" > ~/hosts.nw
echo "8.8.8.8		facebook.com" >> ~/hosts.nw
cp -f ~/hosts.nw /etc/hosts
